using IronPython.Hosting;
using Microsoft.Scripting.Hosting;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Web;

namespace HeCon_webapp.Models
{
    public class PythonCaller
    {
        private static PythonCaller python;

        public static PythonCaller getPythonCaller()
        {
            if (python == null)
                python = new PythonCaller();
            return python;

        }

        public string callPython(string imagePath)
        {

            ProcessStartInfo start = new ProcessStartInfo();
            start.FileName = "C:/Users/Alin/Anaconda3/envs/tensorflow/python.exe";
            start.Arguments = string.Format("\"{0}\" \"{1}\"", "F:\\IP\\HeCon-ml\\script.py", imagePath);
            start.UseShellExecute = false;// Do not use OS shell
            start.CreateNoWindow = true;
            start.WorkingDirectory = "F:\\IP\\HeCon-ml\\";
            start.RedirectStandardOutput = true;// Any output, generated by application will be redirected back
            start.RedirectStandardError = true; // Any error in standard output will be redirected back (for example exceptions)
            using (Process process = Process.Start(start))
            {
                using (StreamReader reader = process.StandardOutput)
                {
                    string stderr = process.StandardError.ReadToEnd(); // Here are the exceptions from our Python script
                    string result = reader.ReadToEnd(); // Here is the result of StdOut(for example: print "test")
                    return result;
                }
            }

        }
    }
}